cd C:\TESTRESOURCES\ALFLOGSEARCH
c:
C:\TESTRESOURCES\ALFLOGSEARCH\[%EXT%] [-p %PHASE%] [-a %APPLICATION%] [-k PK%PEAK%] [-s %TIMEFROM%] [--i=%INTERVAL%] [-r %RECLOC%] [-f %FLIGHT%] [-n %PAXNAME%] [-m %MESSAGE%] [-u %PACCOUNTDETAILS%] [-o %OUTPUT%] [-c %CRITERIA%] 